// Copyright (c) 2026 John Dewey

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package recipes

import (
	"fmt"
	"strings"
)

// render writes a rig as YAML, with the comments a person needs to edit it.
//
// Generated by hand rather than by marshalling a struct: a marshalled rig
// loses the comments, and the comments are most of what makes a scaffold
// worth having over an empty file.
func render(
	opts NewOptions,
) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# %s\n#\n", title(opts))
	b.WriteString("# A rig names real-world gear, never Line 6 model IDs. " +
		"\"Ampeg SVT\"\n")
	b.WriteString("# resolves through the gear map, so this file stays " +
		"readable, stays correct\n")
	b.WriteString("# when Line 6 rename something, and works for any Helix " +
		"device.\n#\n")
	b.WriteString("# See docs/recipes.md.\n\n")

	b.WriteString("schema: RigSpec\nversion: 2\n")
	fmt.Fprintf(&b, "id: %s\n\n", opts.ID)

	fmt.Fprintf(&b, "instrument: %s\n\n", opts.Instrument)

	b.WriteString("# The signal path, in order. Order is what the signal " +
		"does: drive ahead\n# of an amp overdrives its input, drive after it " +
		"is a different sound.\n#\n")
	b.WriteString("# Evidence attaches to the claim it supports, not to the " +
		"file, because the\n# amp may come from an interview and a drive " +
		"figure from measuring a corpus.\n")
	b.WriteString("# `llm` means a model asserted it and nobody checked — " +
		"the largest\n# correctness risk in this project, so say so rather " +
		"than leaving it implied.\nchain:\n")

	b.WriteString(renderPedals(opts.Pedals))
	b.WriteString(entry("amp", opts.Amp))

	if opts.Cab != "" {
		b.WriteString(entry("cab", opts.Cab))
	} else {
		b.WriteString("  # No cabinet named, so the amp's own pairing is " +
			"used — which is what\n  # Line 6 voiced it with.\n")
	}

	return b.String()
}

// renderAsk writes the ask beside the rig, with the same comments.
//
// Who it is for, how it should sound and how far to trust it are all things a
// person wrote, so they are on the ask and not on the gear. Written as a second
// file rather than folded in, because the gear answers the question and the
// question is not a property of the answer.
//
// from is the rig this was copied from, or empty for one scaffolded from gear.
// A fresh ask still records the link, because a copy of a parent that has no ask
// of its own is written from here rather than copied, and leaving `extends` out
// in that one case would mean `recipes show` never listed the copy as a variant
// of the rig it came from. The link is a fact about the copy, not about whether
// the parent happened to have an ask.
func renderAsk(
	opts NewOptions,
	from string,
) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# What %s was asked for.\n#\n", title(opts))
	b.WriteString("# The rig beside this file is what answered it. This one " +
		"says who it is for\n# and how it should sound; that one says what " +
		"the gear is.\n#\n")
	b.WriteString("# See docs/tonespec.md.\n\n")

	b.WriteString("schema: ToneSpec\n")

	if from != "" {
		fmt.Fprintf(&b, "extends: %s\n", from)
	}

	b.WriteString("\n")

	b.WriteString("subject:\n  kind: artist\n")
	fmt.Fprintf(&b, "  name: %s\n", opts.Name)

	if opts.Band != "" {
		fmt.Fprintf(&b, "  band: %s\n", opts.Band)
	}

	// Left out rather than written blank when nothing says. A copy takes its
	// instrument from the rig it came from, and a rig read off a device names
	// one this may not have been told, so the contract refusing an empty string
	// is right and writing one would be the bug.
	if opts.Instrument != "" {
		fmt.Fprintf(&b, "\ninstrument: %s\n", opts.Instrument)
	}

	b.WriteString("\n# How it should sound, in the words a person would " +
		"use. Describe the\n# result, not the control: \"mid-forward\", not " +
		"\"raise the mids\".\nwords: []\n\n")

	b.WriteString("# How far to trust the whole thing. Nothing here has been " +
		"confirmed against\n# a rig rundown, an interview or a recording. " +
		"Correct it from what you hear.\nconfidence: low\n")

	return b.String()
}

// entry writes one piece of gear, with the evidence nobody has supplied yet.
func entry(
	role, gear string,
) string {
	var b strings.Builder

	fmt.Fprintf(&b, "  - role: %s\n    gear: %s\n", role, gear)
	b.WriteString("    evidence:\n      - { kind: llm }\n")
	b.WriteString("    confidence: low\n")

	return b.String()
}

// title names the rig in its own header comment.
func title(
	opts NewOptions,
) string {
	if opts.Band == "" {
		return opts.Name
	}

	return opts.Name + " — " + opts.Band
}

// renderPedals writes the pedals, ahead of the amp.
//
// A scaffold cannot know what a pedal does, so every one is written as
// `drive` for somebody to correct. Guessing a role from a product name would
// be wrong often enough to be worse than obviously blank.
func renderPedals(
	pedals []string,
) string {
	var b strings.Builder

	for _, p := range pedals {
		b.WriteString(entry("drive", p))
	}

	return b.String()
}
