---
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "docs/**"

github:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "go.mod"
          - "go.sum"

marketplace:
  - changed-files:
      - any-glob-to-any-file:
          - "marketplace/**"

source:
  - changed-files:
      - any-glob-to-any-file:
          - "cmd/**"
          - "pkg/**"
          - "main.go"
