// Copyright (c) 2026 John Dewey

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

// Package specdoc writes the page describing what a request may say.
package specdoc

import "github.com/retr0h/tonestack/pkg/sdk/internal/specdoc"

// Page is the part of the page that is about the page.
//
// The only prose anybody has to keep true by hand. Everything below it is the
// contract's own words.
var Page = specdoc.Page{
	Root: "ToneSpec",
	Preamble: `<!-- Generated by pkg/sdk/tone/internal/specdoc. Do not edit. -->

# What a request may say

Every field a ToneSpec and a Setup may carry. Generated from
[the contract](../pkg/sdk/tone/data/tonespec.openapi.yaml), so it cannot drift
from what the code actually enforces.

These are the two documents a person writes, and neither carries a knob
position. A ToneSpec is the ask and changes every request; a Setup is what
somebody owns and changes when they buy something. What they resolve to is
[a RigSpec](rigspec.md), which nobody writes by hand.

` + "```text" + `
ToneSpec + Setup   what we mean, and what we have
      ↓            tonestack tone build
RigSpec            exact, resolved, deterministic, shareable
      ↓            tonestack presets compile
.hlx               what the pedal eats
` + "```" + `

Every field is optional and any combination is legal. "Punk, but on my Jazz"
is a genre and a Setup; "like Dirnt but chunkier" is a player and a nudge. A
request nobody filled in completely is the ordinary case, and what cannot be
answered is reported rather than guessed at.

` + specdoc.Buckets + `
Nothing here is checked against a catalog, because a request names gear the
way a person does and the device it will be built for is a separate question.
That check happens when the rig is compiled.
`,
}
