// Code generated by MockGen. DO NOT EDIT.
// Source: ../types.go
//
// Generated by this command:
//
//	mockgen -source=../types.go -destination=types.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	tools "github.com/retr0h/toneharness/pkg/mcp/internal/tools"
	sdk "github.com/retr0h/toneharness/pkg/sdk"
	audio "github.com/retr0h/toneharness/pkg/sdk/audio"
	catalog "github.com/retr0h/toneharness/pkg/sdk/catalog"
	slot "github.com/retr0h/toneharness/pkg/sdk/slot"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Backing mocks base method.
func (m *MockClient) Backing(ctx context.Context, corpus string) ([]sdk.Backing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backing", ctx, corpus)
	ret0, _ := ret[0].([]sdk.Backing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Backing indicates an expected call of Backing.
func (mr *MockClientMockRecorder) Backing(ctx, corpus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backing", reflect.TypeOf((*MockClient)(nil).Backing), ctx, corpus)
}

// Block mocks base method.
func (m *MockClient) Block(ctx context.Context, id string) (catalog.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Block", ctx, id)
	ret0, _ := ret[0].(catalog.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Block indicates an expected call of Block.
func (mr *MockClientMockRecorder) Block(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Block", reflect.TypeOf((*MockClient)(nil).Block), ctx, id)
}

// Blocks mocks base method.
func (m *MockClient) Blocks(ctx context.Context, f sdk.Filter) (sdk.Blocks, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Blocks", ctx, f)
	ret0, _ := ret[0].(sdk.Blocks)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Blocks indicates an expected call of Blocks.
func (mr *MockClientMockRecorder) Blocks(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blocks", reflect.TypeOf((*MockClient)(nil).Blocks), ctx, f)
}

// ChainMeasurements mocks base method.
func (m *MockClient) ChainMeasurements(ctx context.Context, instrument string) (sdk.Measured, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChainMeasurements", ctx, instrument)
	ret0, _ := ret[0].(sdk.Measured)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChainMeasurements indicates an expected call of ChainMeasurements.
func (mr *MockClientMockRecorder) ChainMeasurements(ctx, instrument any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChainMeasurements", reflect.TypeOf((*MockClient)(nil).ChainMeasurements), ctx, instrument)
}

// Compile mocks base method.
func (m *MockClient) Compile(ctx context.Context, in sdk.Compile) (sdk.Built, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compile", ctx, in)
	ret0, _ := ret[0].(sdk.Built)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compile indicates an expected call of Compile.
func (mr *MockClientMockRecorder) Compile(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compile", reflect.TypeOf((*MockClient)(nil).Compile), ctx, in)
}

// Devices mocks base method.
func (m *MockClient) Devices(ctx context.Context) (sdk.Attached, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Devices", ctx)
	ret0, _ := ret[0].(sdk.Attached)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Devices indicates an expected call of Devices.
func (mr *MockClientMockRecorder) Devices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Devices", reflect.TypeOf((*MockClient)(nil).Devices), ctx)
}

// Make mocks base method.
func (m *MockClient) Make(ctx context.Context, in sdk.Build) (sdk.Made, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", ctx, in)
	ret0, _ := ret[0].(sdk.Made)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Make indicates an expected call of Make.
func (mr *MockClientMockRecorder) Make(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockClient)(nil).Make), ctx, in)
}

// MeasuredGenres mocks base method.
func (m *MockClient) MeasuredGenres(ctx context.Context, corpus string) ([]audio.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MeasuredGenres", ctx, corpus)
	ret0, _ := ret[0].([]audio.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MeasuredGenres indicates an expected call of MeasuredGenres.
func (mr *MockClientMockRecorder) MeasuredGenres(ctx, corpus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MeasuredGenres", reflect.TypeOf((*MockClient)(nil).MeasuredGenres), ctx, corpus)
}

// MeasuredPlayers mocks base method.
func (m *MockClient) MeasuredPlayers(ctx context.Context, corpus string) ([]audio.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MeasuredPlayers", ctx, corpus)
	ret0, _ := ret[0].([]audio.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MeasuredPlayers indicates an expected call of MeasuredPlayers.
func (mr *MockClientMockRecorder) MeasuredPlayers(ctx, corpus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MeasuredPlayers", reflect.TypeOf((*MockClient)(nil).MeasuredPlayers), ctx, corpus)
}

// MeasuredRecordings mocks base method.
func (m *MockClient) MeasuredRecordings(ctx context.Context, dir string) ([]audio.Named, audio.Across, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MeasuredRecordings", ctx, dir)
	ret0, _ := ret[0].([]audio.Named)
	ret1, _ := ret[1].(audio.Across)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// MeasuredRecordings indicates an expected call of MeasuredRecordings.
func (mr *MockClientMockRecorder) MeasuredRecordings(ctx, dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MeasuredRecordings", reflect.TypeOf((*MockClient)(nil).MeasuredRecordings), ctx, dir)
}

// ModelMeasurements mocks base method.
func (m *MockClient) ModelMeasurements(ctx context.Context, model string) (sdk.Measured, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ModelMeasurements", ctx, model)
	ret0, _ := ret[0].(sdk.Measured)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ModelMeasurements indicates an expected call of ModelMeasurements.
func (mr *MockClientMockRecorder) ModelMeasurements(ctx, model any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModelMeasurements", reflect.TypeOf((*MockClient)(nil).ModelMeasurements), ctx, model)
}

// MusicBands mocks base method.
func (m *MockClient) MusicBands(ctx context.Context, corpus string) ([]sdk.MusicGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MusicBands", ctx, corpus)
	ret0, _ := ret[0].([]sdk.MusicGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MusicBands indicates an expected call of MusicBands.
func (mr *MockClientMockRecorder) MusicBands(ctx, corpus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MusicBands", reflect.TypeOf((*MockClient)(nil).MusicBands), ctx, corpus)
}

// MusicGenres mocks base method.
func (m *MockClient) MusicGenres(ctx context.Context, corpus string) ([]sdk.MusicGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MusicGenres", ctx, corpus)
	ret0, _ := ret[0].([]sdk.MusicGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MusicGenres indicates an expected call of MusicGenres.
func (mr *MockClientMockRecorder) MusicGenres(ctx, corpus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MusicGenres", reflect.TypeOf((*MockClient)(nil).MusicGenres), ctx, corpus)
}

// MusicPlayers mocks base method.
func (m *MockClient) MusicPlayers(ctx context.Context, corpus string) ([]sdk.MusicPlayer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MusicPlayers", ctx, corpus)
	ret0, _ := ret[0].([]sdk.MusicPlayer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MusicPlayers indicates an expected call of MusicPlayers.
func (mr *MockClientMockRecorder) MusicPlayers(ctx, corpus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MusicPlayers", reflect.TypeOf((*MockClient)(nil).MusicPlayers), ctx, corpus)
}

// MusicRecords mocks base method.
func (m *MockClient) MusicRecords(ctx context.Context, corpus string) ([]sdk.MusicRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MusicRecords", ctx, corpus)
	ret0, _ := ret[0].([]sdk.MusicRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MusicRecords indicates an expected call of MusicRecords.
func (mr *MockClientMockRecorder) MusicRecords(ctx, corpus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MusicRecords", reflect.TypeOf((*MockClient)(nil).MusicRecords), ctx, corpus)
}

// Open mocks base method.
func (m *MockClient) Open(ctx context.Context) (tools.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", ctx)
	ret0, _ := ret[0].(tools.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockClientMockRecorder) Open(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockClient)(nil).Open), ctx)
}

// Resolve mocks base method.
func (m *MockClient) Resolve(ctx context.Context, in sdk.Resolve) (sdk.Made, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx, in)
	ret0, _ := ret[0].(sdk.Made)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockClientMockRecorder) Resolve(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockClient)(nil).Resolve), ctx, in)
}

// Rig mocks base method.
func (m *MockClient) Rig(ctx context.Context, id string) (sdk.Rig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rig", ctx, id)
	ret0, _ := ret[0].(sdk.Rig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rig indicates an expected call of Rig.
func (mr *MockClientMockRecorder) Rig(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rig", reflect.TypeOf((*MockClient)(nil).Rig), ctx, id)
}

// Rigs mocks base method.
func (m *MockClient) Rigs(ctx context.Context) (sdk.Rigs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rigs", ctx)
	ret0, _ := ret[0].(sdk.Rigs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rigs indicates an expected call of Rigs.
func (mr *MockClientMockRecorder) Rigs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rigs", reflect.TypeOf((*MockClient)(nil).Rigs), ctx)
}

// Scaffold mocks base method.
func (m *MockClient) Scaffold(ctx context.Context, in sdk.NewRig) (sdk.Scaffolded, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scaffold", ctx, in)
	ret0, _ := ret[0].(sdk.Scaffolded)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scaffold indicates an expected call of Scaffold.
func (mr *MockClientMockRecorder) Scaffold(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scaffold", reflect.TypeOf((*MockClient)(nil).Scaffold), ctx, in)
}

// Tone mocks base method.
func (m *MockClient) Tone(ctx context.Context, in sdk.Ask) (sdk.Resolved, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tone", ctx, in)
	ret0, _ := ret[0].(sdk.Resolved)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tone indicates an expected call of Tone.
func (mr *MockClientMockRecorder) Tone(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tone", reflect.TypeOf((*MockClient)(nil).Tone), ctx, in)
}

// MockSession is a mock of Session interface.
type MockSession struct {
	ctrl     *gomock.Controller
	recorder *MockSessionMockRecorder
	isgomock struct{}
}

// MockSessionMockRecorder is the mock recorder for MockSession.
type MockSessionMockRecorder struct {
	mock *MockSession
}

// NewMockSession creates a new mock instance.
func NewMockSession(ctrl *gomock.Controller) *MockSession {
	mock := &MockSession{ctrl: ctrl}
	mock.recorder = &MockSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSession) EXPECT() *MockSessionMockRecorder {
	return m.recorder
}

// Choose mocks base method.
func (m *MockSession) Choose(ctx context.Context, at sdk.Address, value int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Choose", ctx, at, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Choose indicates an expected call of Choose.
func (mr *MockSessionMockRecorder) Choose(ctx, at, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Choose", reflect.TypeOf((*MockSession)(nil).Choose), ctx, at, value)
}

// Close mocks base method.
func (m *MockSession) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSessionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSession)(nil).Close))
}

// Copy mocks base method.
func (m *MockSession) Copy(ctx context.Context, from, to slot.Address) (sdk.Change, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", ctx, from, to)
	ret0, _ := ret[0].(sdk.Change)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Copy indicates an expected call of Copy.
func (mr *MockSessionMockRecorder) Copy(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockSession)(nil).Copy), ctx, from, to)
}

// Current mocks base method.
func (m *MockSession) Current(ctx context.Context, as sdk.Format) (sdk.Reading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current", ctx, as)
	ret0, _ := ret[0].(sdk.Reading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Current indicates an expected call of Current.
func (mr *MockSessionMockRecorder) Current(ctx, as any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockSession)(nil).Current), ctx, as)
}

// Export mocks base method.
func (m *MockSession) Export(ctx context.Context, at slot.Address, out string, as sdk.Format, existing sdk.Existing) (sdk.Written, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Export", ctx, at, out, as, existing)
	ret0, _ := ret[0].(sdk.Written)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Export indicates an expected call of Export.
func (mr *MockSessionMockRecorder) Export(ctx, at, out, as, existing any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Export", reflect.TypeOf((*MockSession)(nil).Export), ctx, at, out, as, existing)
}

// Import mocks base method.
func (m *MockSession) Import(ctx context.Context, file string, at slot.Address) (sdk.Change, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Import", ctx, file, at)
	ret0, _ := ret[0].(sdk.Change)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Import indicates an expected call of Import.
func (mr *MockSessionMockRecorder) Import(ctx, file, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Import", reflect.TypeOf((*MockSession)(nil).Import), ctx, file, at)
}

// Play mocks base method.
func (m *MockSession) Play(ctx context.Context, file string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Play", ctx, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// Play indicates an expected call of Play.
func (mr *MockSessionMockRecorder) Play(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Play", reflect.TypeOf((*MockSession)(nil).Play), ctx, file)
}

// Preset mocks base method.
func (m *MockSession) Preset(ctx context.Context, at slot.Address) (sdk.Reading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Preset", ctx, at)
	ret0, _ := ret[0].(sdk.Reading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Preset indicates an expected call of Preset.
func (mr *MockSessionMockRecorder) Preset(ctx, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Preset", reflect.TypeOf((*MockSession)(nil).Preset), ctx, at)
}

// Presets mocks base method.
func (m *MockSession) Presets(ctx context.Context, setlist int) (sdk.Listing, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Presets", ctx, setlist)
	ret0, _ := ret[0].(sdk.Listing)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Presets indicates an expected call of Presets.
func (mr *MockSessionMockRecorder) Presets(ctx, setlist any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Presets", reflect.TypeOf((*MockSession)(nil).Presets), ctx, setlist)
}

// Select mocks base method.
func (m *MockSession) Select(ctx context.Context, at slot.Address) (sdk.Change, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", ctx, at)
	ret0, _ := ret[0].(sdk.Change)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select.
func (mr *MockSessionMockRecorder) Select(ctx, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockSession)(nil).Select), ctx, at)
}

// Swap mocks base method.
func (m *MockSession) Swap(ctx context.Context, a, b slot.Address) (sdk.Change, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Swap", ctx, a, b)
	ret0, _ := ret[0].(sdk.Change)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Swap indicates an expected call of Swap.
func (mr *MockSessionMockRecorder) Swap(ctx, a, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Swap", reflect.TypeOf((*MockSession)(nil).Swap), ctx, a, b)
}

// Switch mocks base method.
func (m *MockSession) Switch(ctx context.Context, at sdk.Address, on bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Switch", ctx, at, on)
	ret0, _ := ret[0].(error)
	return ret0
}

// Switch indicates an expected call of Switch.
func (mr *MockSessionMockRecorder) Switch(ctx, at, on any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Switch", reflect.TypeOf((*MockSession)(nil).Switch), ctx, at, on)
}

// Turn mocks base method.
func (m *MockSession) Turn(ctx context.Context, at sdk.Address, value float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Turn", ctx, at, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Turn indicates an expected call of Turn.
func (mr *MockSessionMockRecorder) Turn(ctx, at, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Turn", reflect.TypeOf((*MockSession)(nil).Turn), ctx, at, value)
}
