// Code generated by MockGen. DO NOT EDIT.
// Source: pedal.go
//
// Generated by this command:
//
//	mockgen -source=pedal.go -destination=internal/mocks/pedal.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sdk "github.com/retr0h/tonestack/pkg/sdk"
	gomock "go.uber.org/mock/gomock"
)

// MockPedal is a mock of Pedal interface.
type MockPedal struct {
	ctrl     *gomock.Controller
	recorder *MockPedalMockRecorder
	isgomock struct{}
}

// MockPedalMockRecorder is the mock recorder for MockPedal.
type MockPedalMockRecorder struct {
	mock *MockPedal
}

// NewMockPedal creates a new mock instance.
func NewMockPedal(ctrl *gomock.Controller) *MockPedal {
	mock := &MockPedal{ctrl: ctrl}
	mock.recorder = &MockPedalMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPedal) EXPECT() *MockPedalMockRecorder {
	return m.recorder
}

// Choose mocks base method.
func (m *MockPedal) Choose(ctx context.Context, at sdk.Address, value int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Choose", ctx, at, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Choose indicates an expected call of Choose.
func (mr *MockPedalMockRecorder) Choose(ctx, at, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Choose", reflect.TypeOf((*MockPedal)(nil).Choose), ctx, at, value)
}

// Compile mocks base method.
func (m *MockPedal) Compile(ctx context.Context, in sdk.Compile) (sdk.Built, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compile", ctx, in)
	ret0, _ := ret[0].(sdk.Built)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compile indicates an expected call of Compile.
func (mr *MockPedalMockRecorder) Compile(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compile", reflect.TypeOf((*MockPedal)(nil).Compile), ctx, in)
}

// Current mocks base method.
func (m *MockPedal) Current(ctx context.Context, as sdk.Format) (sdk.Reading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current", ctx, as)
	ret0, _ := ret[0].(sdk.Reading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Current indicates an expected call of Current.
func (mr *MockPedalMockRecorder) Current(ctx, as any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockPedal)(nil).Current), ctx, as)
}

// Play mocks base method.
func (m *MockPedal) Play(ctx context.Context, file string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Play", ctx, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// Play indicates an expected call of Play.
func (mr *MockPedalMockRecorder) Play(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Play", reflect.TypeOf((*MockPedal)(nil).Play), ctx, file)
}

// Turn mocks base method.
func (m *MockPedal) Turn(ctx context.Context, at sdk.Address, value float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Turn", ctx, at, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Turn indicates an expected call of Turn.
func (mr *MockPedalMockRecorder) Turn(ctx, at, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Turn", reflect.TypeOf((*MockPedal)(nil).Turn), ctx, at, value)
}
