// Code generated by MockGen. DO NOT EDIT.
// Source: tone_reach.go
//
// Generated by this command:
//
//	mockgen -source=tone_reach.go -destination=internal/mocks/reaches.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sdk "github.com/retr0h/toneharness/pkg/sdk"
	gomock "go.uber.org/mock/gomock"
)

// MockReaches is a mock of Reaches interface.
type MockReaches struct {
	ctrl     *gomock.Controller
	recorder *MockReachesMockRecorder
	isgomock struct{}
}

// MockReachesMockRecorder is the mock recorder for MockReaches.
type MockReachesMockRecorder struct {
	mock *MockReaches
}

// NewMockReaches creates a new mock instance.
func NewMockReaches(ctrl *gomock.Controller) *MockReaches {
	mock := &MockReaches{ctrl: ctrl}
	mock.recorder = &MockReachesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReaches) EXPECT() *MockReachesMockRecorder {
	return m.recorder
}

// Reach mocks base method.
func (m *MockReaches) Reach(ctx context.Context, in sdk.ReachAsk) (sdk.Reaching, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reach", ctx, in)
	ret0, _ := ret[0].(sdk.Reaching)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reach indicates an expected call of Reach.
func (mr *MockReachesMockRecorder) Reach(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reach", reflect.TypeOf((*MockReaches)(nil).Reach), ctx, in)
}
