// Code generated by MockGen. DO NOT EDIT.
// Source: tone_build.go
//
// Generated by this command:
//
//	mockgen -source=tone_build.go -destination=internal/mocks/resolver.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sdk "github.com/retr0h/toneharness/pkg/sdk"
	gomock "go.uber.org/mock/gomock"
)

// MockResolver is a mock of Resolver interface.
type MockResolver struct {
	ctrl     *gomock.Controller
	recorder *MockResolverMockRecorder
	isgomock struct{}
}

// MockResolverMockRecorder is the mock recorder for MockResolver.
type MockResolverMockRecorder struct {
	mock *MockResolver
}

// NewMockResolver creates a new mock instance.
func NewMockResolver(ctrl *gomock.Controller) *MockResolver {
	mock := &MockResolver{ctrl: ctrl}
	mock.recorder = &MockResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResolver) EXPECT() *MockResolverMockRecorder {
	return m.recorder
}

// Tone mocks base method.
func (m *MockResolver) Tone(ctx context.Context, in sdk.Ask) (sdk.Resolved, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tone", ctx, in)
	ret0, _ := ret[0].(sdk.Resolved)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Tone indicates an expected call of Tone.
func (mr *MockResolverMockRecorder) Tone(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tone", reflect.TypeOf((*MockResolver)(nil).Tone), ctx, in)
}
