// Code generated by MockGen. DO NOT EDIT.
// Source: ../../tone_tune.go
//
// Generated by this command:
//
//	mockgen -source=../../tone_tune.go -destination=tuner.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	sdk "github.com/retr0h/toneharness/pkg/sdk"
	audio "github.com/retr0h/toneharness/pkg/sdk/audio"
	catalog "github.com/retr0h/toneharness/pkg/sdk/catalog"
	gomock "go.uber.org/mock/gomock"
)

// MockBuilds is a mock of Builds interface.
type MockBuilds struct {
	ctrl     *gomock.Controller
	recorder *MockBuildsMockRecorder
	isgomock struct{}
}

// MockBuildsMockRecorder is the mock recorder for MockBuilds.
type MockBuildsMockRecorder struct {
	mock *MockBuilds
}

// NewMockBuilds creates a new mock instance.
func NewMockBuilds(ctrl *gomock.Controller) *MockBuilds {
	mock := &MockBuilds{ctrl: ctrl}
	mock.recorder = &MockBuildsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuilds) EXPECT() *MockBuildsMockRecorder {
	return m.recorder
}

// Make mocks base method.
func (m *MockBuilds) Make(ctx context.Context, in sdk.Build) (sdk.Made, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", ctx, in)
	ret0, _ := ret[0].(sdk.Made)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Make indicates an expected call of Make.
func (mr *MockBuildsMockRecorder) Make(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockBuilds)(nil).Make), ctx, in)
}

// MockTuner is a mock of Tuner interface.
type MockTuner struct {
	ctrl     *gomock.Controller
	recorder *MockTunerMockRecorder
	isgomock struct{}
}

// MockTunerMockRecorder is the mock recorder for MockTuner.
type MockTunerMockRecorder struct {
	mock *MockTuner
}

// NewMockTuner creates a new mock instance.
func NewMockTuner(ctrl *gomock.Controller) *MockTuner {
	mock := &MockTuner{ctrl: ctrl}
	mock.recorder = &MockTunerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTuner) EXPECT() *MockTunerMockRecorder {
	return m.recorder
}

// Catalog mocks base method.
func (m *MockTuner) Catalog(ctx context.Context) (*catalog.Catalog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Catalog", ctx)
	ret0, _ := ret[0].(*catalog.Catalog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Catalog indicates an expected call of Catalog.
func (mr *MockTunerMockRecorder) Catalog(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Catalog", reflect.TypeOf((*MockTuner)(nil).Catalog), ctx)
}

// Choose mocks base method.
func (m *MockTuner) Choose(ctx context.Context, at sdk.Address, value int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Choose", ctx, at, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Choose indicates an expected call of Choose.
func (mr *MockTunerMockRecorder) Choose(ctx, at, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Choose", reflect.TypeOf((*MockTuner)(nil).Choose), ctx, at, value)
}

// Compile mocks base method.
func (m *MockTuner) Compile(ctx context.Context, in sdk.Compile) (sdk.Built, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compile", ctx, in)
	ret0, _ := ret[0].(sdk.Built)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compile indicates an expected call of Compile.
func (mr *MockTunerMockRecorder) Compile(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compile", reflect.TypeOf((*MockTuner)(nil).Compile), ctx, in)
}

// Current mocks base method.
func (m *MockTuner) Current(ctx context.Context, as sdk.Format) (sdk.Reading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Current", ctx, as)
	ret0, _ := ret[0].(sdk.Reading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Current indicates an expected call of Current.
func (mr *MockTunerMockRecorder) Current(ctx, as any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Current", reflect.TypeOf((*MockTuner)(nil).Current), ctx, as)
}

// Make mocks base method.
func (m *MockTuner) Make(ctx context.Context, in sdk.Build) (sdk.Made, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Make", ctx, in)
	ret0, _ := ret[0].(sdk.Made)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Make indicates an expected call of Make.
func (mr *MockTunerMockRecorder) Make(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Make", reflect.TypeOf((*MockTuner)(nil).Make), ctx, in)
}

// Play mocks base method.
func (m *MockTuner) Play(ctx context.Context, file string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Play", ctx, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// Play indicates an expected call of Play.
func (mr *MockTunerMockRecorder) Play(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Play", reflect.TypeOf((*MockTuner)(nil).Play), ctx, file)
}

// PresetFile mocks base method.
func (m *MockTuner) PresetFile(ctx context.Context, path string) (sdk.Reading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PresetFile", ctx, path)
	ret0, _ := ret[0].(sdk.Reading)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PresetFile indicates an expected call of PresetFile.
func (mr *MockTunerMockRecorder) PresetFile(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PresetFile", reflect.TypeOf((*MockTuner)(nil).PresetFile), ctx, path)
}

// Switch mocks base method.
func (m *MockTuner) Switch(ctx context.Context, at sdk.Address, on bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Switch", ctx, at, on)
	ret0, _ := ret[0].(error)
	return ret0
}

// Switch indicates an expected call of Switch.
func (mr *MockTunerMockRecorder) Switch(ctx, at, on any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Switch", reflect.TypeOf((*MockTuner)(nil).Switch), ctx, at, on)
}

// Turn mocks base method.
func (m *MockTuner) Turn(ctx context.Context, at sdk.Address, value float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Turn", ctx, at, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Turn indicates an expected call of Turn.
func (mr *MockTunerMockRecorder) Turn(ctx, at, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Turn", reflect.TypeOf((*MockTuner)(nil).Turn), ctx, at, value)
}

// MockGenres is a mock of Genres interface.
type MockGenres struct {
	ctrl     *gomock.Controller
	recorder *MockGenresMockRecorder
	isgomock struct{}
}

// MockGenresMockRecorder is the mock recorder for MockGenres.
type MockGenresMockRecorder struct {
	mock *MockGenres
}

// NewMockGenres creates a new mock instance.
func NewMockGenres(ctrl *gomock.Controller) *MockGenres {
	mock := &MockGenres{ctrl: ctrl}
	mock.recorder = &MockGenresMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenres) EXPECT() *MockGenresMockRecorder {
	return m.recorder
}

// MeasuredGenres mocks base method.
func (m *MockGenres) MeasuredGenres(ctx context.Context, corpus string) ([]audio.Genre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MeasuredGenres", ctx, corpus)
	ret0, _ := ret[0].([]audio.Genre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MeasuredGenres indicates an expected call of MeasuredGenres.
func (mr *MockGenresMockRecorder) MeasuredGenres(ctx, corpus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MeasuredGenres", reflect.TypeOf((*MockGenres)(nil).MeasuredGenres), ctx, corpus)
}

// MockRecorded is a mock of Recorded interface.
type MockRecorded struct {
	ctrl     *gomock.Controller
	recorder *MockRecordedMockRecorder
	isgomock struct{}
}

// MockRecordedMockRecorder is the mock recorder for MockRecorded.
type MockRecordedMockRecorder struct {
	mock *MockRecorded
}

// NewMockRecorded creates a new mock instance.
func NewMockRecorded(ctrl *gomock.Controller) *MockRecorded {
	mock := &MockRecorded{ctrl: ctrl}
	mock.recorder = &MockRecordedMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecorded) EXPECT() *MockRecordedMockRecorder {
	return m.recorder
}

// MeasuredPlayers mocks base method.
func (m *MockRecorded) MeasuredPlayers(ctx context.Context, corpus string) ([]audio.Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MeasuredPlayers", ctx, corpus)
	ret0, _ := ret[0].([]audio.Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MeasuredPlayers indicates an expected call of MeasuredPlayers.
func (mr *MockRecordedMockRecorder) MeasuredPlayers(ctx, corpus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MeasuredPlayers", reflect.TypeOf((*MockRecorded)(nil).MeasuredPlayers), ctx, corpus)
}
