// Copyright (c) 2026 John Dewey

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

// Package specdoc writes the RigSpec grammar page.
package specdoc

import "github.com/retr0h/tonestack/pkg/sdk/internal/specdoc"

// Page is the part of the grammar page that is about the page.
//
// The only prose anybody has to keep true by hand. Everything below it is the
// contract's own words.
var Page = specdoc.Page{
	Root: "RigSpec",
	Preamble: `<!-- Generated by pkg/sdk/rig/internal/specdoc. Do not edit. -->

# The RigSpec grammar

Every field a rig may carry, and what it may say. Generated from
[the contract](../pkg/sdk/rig/data/rigspec.openapi.yaml), so it cannot drift
from what the code actually enforces.

A rig is not the document somebody writes. It is what
[a ToneSpec](tonespec.md) resolves to, and what a preset is compiled from:
exact model identifiers, deterministic, and the layer worth sharing because
two people compiling one get the same preset.

` + specdoc.Buckets + `
Reading a rig checks the closed and shaped fields. Building one checks the
looked-up fields as well, because only then is there a catalog to check them
against.
`,
}
