// Code generated by MockGen. DO NOT EDIT.
// Source: ../types.go
//
// Generated by this command:
//
//	mockgen -source=../types.go -destination=types.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	catalog "github.com/retr0h/toneharness/pkg/sdk/catalog"
	corpus "github.com/retr0h/toneharness/pkg/sdk/corpus"
	compile "github.com/retr0h/toneharness/pkg/sdk/internal/compile"
	rigs "github.com/retr0h/toneharness/pkg/sdk/internal/rigs"
	plan "github.com/retr0h/toneharness/pkg/sdk/plan"
	preset "github.com/retr0h/toneharness/pkg/sdk/preset"
	result "github.com/retr0h/toneharness/pkg/sdk/result"
	rig "github.com/retr0h/toneharness/pkg/sdk/rig"
	gomock "go.uber.org/mock/gomock"
)

// MockCatalogs is a mock of Catalogs interface.
type MockCatalogs struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogsMockRecorder
	isgomock struct{}
}

// MockCatalogsMockRecorder is the mock recorder for MockCatalogs.
type MockCatalogsMockRecorder struct {
	mock *MockCatalogs
}

// NewMockCatalogs creates a new mock instance.
func NewMockCatalogs(ctrl *gomock.Controller) *MockCatalogs {
	mock := &MockCatalogs{ctrl: ctrl}
	mock.recorder = &MockCatalogsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogs) EXPECT() *MockCatalogsMockRecorder {
	return m.recorder
}

// Catalog mocks base method.
func (m *MockCatalogs) Catalog(ctx context.Context) (*catalog.Catalog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Catalog", ctx)
	ret0, _ := ret[0].(*catalog.Catalog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Catalog indicates an expected call of Catalog.
func (mr *MockCatalogsMockRecorder) Catalog(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Catalog", reflect.TypeOf((*MockCatalogs)(nil).Catalog), ctx)
}

// MockRigs is a mock of Rigs interface.
type MockRigs struct {
	ctrl     *gomock.Controller
	recorder *MockRigsMockRecorder
	isgomock struct{}
}

// MockRigsMockRecorder is the mock recorder for MockRigs.
type MockRigsMockRecorder struct {
	mock *MockRigs
}

// NewMockRigs creates a new mock instance.
func NewMockRigs(ctrl *gomock.Controller) *MockRigs {
	mock := &MockRigs{ctrl: ctrl}
	mock.recorder = &MockRigsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRigs) EXPECT() *MockRigsMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockRigs) Find(src rigs.Source, id string) (result.Known, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", src, id)
	ret0, _ := ret[0].(result.Known)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRigsMockRecorder) Find(src, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRigs)(nil).Find), src, id)
}

// MockCompiler is a mock of Compiler interface.
type MockCompiler struct {
	ctrl     *gomock.Controller
	recorder *MockCompilerMockRecorder
	isgomock struct{}
}

// MockCompilerMockRecorder is the mock recorder for MockCompiler.
type MockCompilerMockRecorder struct {
	mock *MockCompiler
}

// NewMockCompiler creates a new mock instance.
func NewMockCompiler(ctrl *gomock.Controller) *MockCompiler {
	mock := &MockCompiler{ctrl: ctrl}
	mock.recorder = &MockCompilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompiler) EXPECT() *MockCompilerMockRecorder {
	return m.recorder
}

// Controllers mocks base method.
func (m *MockCompiler) Controllers(doc *preset.Document, made plan.Plan, blocks []plan.Block, cat *catalog.Catalog) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Controllers", doc, made, blocks, cat)
}

// Controllers indicates an expected call of Controllers.
func (mr *MockCompilerMockRecorder) Controllers(doc, made, blocks, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Controllers", reflect.TypeOf((*MockCompiler)(nil).Controllers), doc, made, blocks, cat)
}

// Fit mocks base method.
func (m *MockCompiler) Fit(spec plan.Plan, cat *catalog.Catalog, lim plan.Limits) plan.Plan {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fit", spec, cat, lim)
	ret0, _ := ret[0].(plan.Plan)
	return ret0
}

// Fit indicates an expected call of Fit.
func (mr *MockCompilerMockRecorder) Fit(spec, cat, lim any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fit", reflect.TypeOf((*MockCompiler)(nil).Fit), spec, cat, lim)
}

// Footswitches mocks base method.
func (m *MockCompiler) Footswitches(doc *preset.Document, made plan.Plan, cat *catalog.Catalog) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Footswitches", doc, made, cat)
}

// Footswitches indicates an expected call of Footswitches.
func (mr *MockCompilerMockRecorder) Footswitches(doc, made, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Footswitches", reflect.TypeOf((*MockCompiler)(nil).Footswitches), doc, made, cat)
}

// Lower mocks base method.
func (m *MockCompiler) Lower(doc *preset.Document, made plan.Plan, cat *catalog.Catalog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lower", doc, made, cat)
	ret0, _ := ret[0].(error)
	return ret0
}

// Lower indicates an expected call of Lower.
func (mr *MockCompilerMockRecorder) Lower(doc, made, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lower", reflect.TypeOf((*MockCompiler)(nil).Lower), doc, made, cat)
}

// Moves mocks base method.
func (m *MockCompiler) Moves(made *plan.Plan, spec rig.Spec, blocks []plan.Block, cat *catalog.Catalog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Moves", made, spec, blocks, cat)
	ret0, _ := ret[0].(error)
	return ret0
}

// Moves indicates an expected call of Moves.
func (mr *MockCompilerMockRecorder) Moves(made, spec, blocks, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Moves", reflect.TypeOf((*MockCompiler)(nil).Moves), made, spec, blocks, cat)
}

// Realise mocks base method.
func (m *MockCompiler) Realise(spec rig.Spec, cat *catalog.Catalog) (plan.Plan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Realise", spec, cat)
	ret0, _ := ret[0].(plan.Plan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Realise indicates an expected call of Realise.
func (mr *MockCompilerMockRecorder) Realise(spec, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Realise", reflect.TypeOf((*MockCompiler)(nil).Realise), spec, cat)
}

// Resolve mocks base method.
func (m *MockCompiler) Resolve(spec rig.Spec, intent compile.Intent, cat *catalog.Catalog, stats *corpus.Stats) (plan.Plan, []compile.Added, []compile.Moved, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", spec, intent, cat, stats)
	ret0, _ := ret[0].(plan.Plan)
	ret1, _ := ret[1].([]compile.Added)
	ret2, _ := ret[2].([]compile.Moved)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Resolve indicates an expected call of Resolve.
func (mr *MockCompilerMockRecorder) Resolve(spec, intent, cat, stats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockCompiler)(nil).Resolve), spec, intent, cat, stats)
}

// Sections mocks base method.
func (m *MockCompiler) Sections(doc *preset.Document, spec rig.Spec, made plan.Plan, blocks []plan.Block, cat *catalog.Catalog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sections", doc, spec, made, blocks, cat)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sections indicates an expected call of Sections.
func (mr *MockCompilerMockRecorder) Sections(doc, spec, made, blocks, cat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sections", reflect.TypeOf((*MockCompiler)(nil).Sections), doc, spec, made, blocks, cat)
}
