// Copyright (c) 2026 John Dewey

// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

package rigs

import (
	"fmt"
	"strings"
)

// render writes a document as YAML, with the comments a person needs to edit
// it.
//
// Generated by hand rather than by marshalling a struct: a marshalled document
// loses the comments, and the comments are most of what makes a scaffold worth
// having over an empty file.
//
// One document, ask first and rig second. The ask is the question and the rig is
// the answer, and somebody opening the file is looking for the question.
func render(
	opts NewOptions,
) string {
	var b strings.Builder

	fmt.Fprintf(&b, "# %s\n#\n", title(opts))
	b.WriteString("# A rig names real-world gear, never Line 6 model IDs. " +
		"\"Ampeg SVT\"\n")
	b.WriteString("# resolves through the gear map, so this file stays " +
		"readable, stays correct\n")
	b.WriteString("# when Line 6 rename something, and works for any Helix " +
		"device.\n#\n")
	b.WriteString("# See the write-a-spec skill.\n\n")

	b.WriteString("schema: ToneSpec\n")
	fmt.Fprintf(&b, "id: %s\n\n", opts.ID)

	b.WriteString(renderAsk(opts, ""))
	b.WriteString("\n")
	b.WriteString(renderRig(opts))

	return b.String()
}

// renderAsk writes the ask section, indented under `ask:`.
//
// Who it is for, how it should sound and how far to trust it are all things a
// person wrote, so they are in the ask and not in the gear. It was a second file
// until version 2, which meant a pair could be half written.
//
// from is the rig this was copied from, or empty for one scaffolded from gear.
// A fresh ask still records the link, because a copy of a parent that has no ask
// of its own is written from here rather than copied, and leaving `extends` out
// in that one case would mean `rigs show` never listed the copy as a variant
// of the rig it came from. The link is a fact about the copy, not about whether
// the parent happened to have an ask.
func renderAsk(
	opts NewOptions,
	from string,
) string {
	var b strings.Builder

	b.WriteString("# What this was asked for. The rig below is what " +
		"answered it.\n#\n")
	b.WriteString("# See pkg/sdk/tone/data/tonespec.openapi.yaml.\nask:\n")

	if from != "" {
		fmt.Fprintf(&b, "  extends: %s\n", from)
	}

	// Before the subject, because it is required and a reader should meet it
	// first. Written as a list whatever its length: a sound belongs to more than
	// one genre often enough that the shape should not change with the count.
	b.WriteString("  genre: [" + strings.Join(opts.Genre, ", ") + "]\n\n")

	b.WriteString("  subject:\n    kind: artist\n")
	fmt.Fprintf(&b, "    name: %s\n", subjectName(opts))

	if opts.Band != "" {
		fmt.Fprintf(&b, "    band: %s\n", opts.Band)
	}

	// Left out rather than written blank when nothing says. A copy takes its
	// instrument from the rig it came from, and a rig read off a device names
	// one this may not have been told, so the contract refusing an empty string
	// is right and writing one would be the bug.
	if opts.Instrument != "" {
		fmt.Fprintf(&b, "\n  instrument: %s\n", opts.Instrument)
	}

	b.WriteString("\n  # How it should sound, in the words a person would " +
		"use. Describe the\n  # result, not the control: \"mid-forward\", not " +
		"\"raise the mids\".\n  words: []\n\n")

	b.WriteString("  # How far to trust the whole thing. Nothing here has been " +
		"confirmed\n  # against a rig rundown, an interview or a recording. " +
		"Correct it from\n  # what you hear.\n  confidence: low\n")

	return b.String()
}

// renderRig writes the rig section, indented under `rig:`.
func renderRig(
	opts NewOptions,
) string {
	var b strings.Builder

	b.WriteString("# The gear that answers it.\nrig:\n")
	fmt.Fprintf(&b, "  instrument: %s\n\n", opts.Instrument)

	b.WriteString("  # The signal path, in order. Order is what the signal " +
		"does: drive ahead\n  # of an amp overdrives its input, drive after " +
		"it is a different sound.\n  #\n")
	b.WriteString("  # Evidence attaches to the claim it supports, not to the " +
		"file, because\n  # the amp may come from an interview and a drive " +
		"figure from measuring a\n  # corpus.\n")
	b.WriteString("  # `llm` means a model asserted it and nobody checked — " +
		"the largest\n  # correctness risk in this project, so say so rather " +
		"than leaving it\n  # implied.\n  chain:\n")

	b.WriteString(renderPedals(opts.Pedals))
	b.WriteString(entry("amp", opts.Amp))

	if opts.Cab != "" {
		b.WriteString(entry("cab", opts.Cab))
	} else {
		b.WriteString("    # No cabinet named, so the amp's own pairing is " +
			"used — which is\n    # what Line 6 voiced it with.\n")
	}

	return b.String()
}

// entry writes one piece of gear, with the evidence nobody has supplied yet.
func entry(
	role, gear string,
) string {
	var b strings.Builder

	fmt.Fprintf(&b, "    - role: %s\n      gear: %s\n", role, gear)
	b.WriteString("      evidence:\n        - { kind: llm }\n")
	b.WriteString("      confidence: low\n")

	return b.String()
}

// title names the rig in its own header comment.
func title(
	opts NewOptions,
) string {
	if opts.Band == "" {
		return subjectName(opts)
	}

	return subjectName(opts) + " — " + opts.Band
}

// subjectName is who the ask is for.
//
// The contract requires it, so it cannot be left out the way the instrument is.
// Without a name the identifier is the only thing that says who this is for, and
// an identifier is a name with the spaces taken out, so it is put back:
// `justin-chancellor` reads as `Justin Chancellor`. Somebody correcting the
// capitals is a smaller job than a scaffold that wrote the field blank, which
// writes a document the loader refuses with nothing saying why.
func subjectName(
	opts NewOptions,
) string {
	if opts.Name != "" {
		return opts.Name
	}

	words := strings.Split(opts.ID, "-")
	for i, w := range words {
		if w == "" {
			continue
		}

		r := []rune(w)
		words[i] = strings.ToUpper(string(r[0])) + string(r[1:])
	}

	return strings.Join(words, " ")
}

// renderPedals writes the pedals, ahead of the amp.
//
// A scaffold cannot know what a pedal does, so every one is written as
// `drive` for somebody to correct. Guessing a role from a product name would
// be wrong often enough to be worse than obviously blank.
func renderPedals(
	pedals []string,
) string {
	var b strings.Builder

	for _, p := range pedals {
		b.WriteString(entry("drive", p))
	}

	return b.String()
}
